version: "2"
services:
  nginx:
   container_name: v-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf:/etc/nginx
   - ./nginx/html:/usr/share/nginx/html
    
  mysql:
   container_name: v-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: house
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   volumes:
   - ./mysql/init:/docker-entrypoint-initdb.d/
   - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
   restart: always
    
  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "9002"
    depends_on:
      - nginx
      - mysql