server:
  port: 9002
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/house?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
      initialize: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.house.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.house.repository: DEBUG